### ISSUE TITLE
Thank you for this project!

### ISSUE THREAD

**Issue by davidmehren** [freehuntx/gpn-tron#13]
Hi!

I just wanted to thank you for publishing this project.
After playing your Tron at GPN, we at [FOSS-AG](https://foss-ag.de) were inspired to organize a hackathon based on it. So we took your code, changed a bunch of things and hosted a [great event](https://hackatron.de) last Friday.

Our fork is now published at https://gitlab.fachschaften.org/foss-ag/hackatron

**Comment by freehuntx** [comment]
Glad you liked it :)
