### ISSUE TITLE
Restore password of user

### ISSUE THREAD

**Issue by EinDev** [freehuntx/gpn-tron#14]
I have played the gpntron last year and this year I wanted to run my code again, but it seems to have remembered the password from last year.

Is there any way to reset a user?

It was not obvious to me that it would be a long-living password, so I just deleted it.

**Comment by EinDev** [comment]
Nevermind :D

**Comment by freehuntx** [comment]
Just to add, this cannot be. I reset the whole machine and the passwords are stored in a local file.
So i guess it was already created by somebody else 😓 Or you just failed :D

**Comment by EinDev** [comment]
I just mistook the error message as "the password is wrong" instead of "the password is not in a valid format, because it starts with a newline character"

So everything is fine :)
