### ISSUE TITLE
List errormessages and doc what they mean?

### ISSUE THREAD

**Issue by noppelmax** [freehuntx/gpn-tron#9]
Which error messages exist?

I have seen

- MAX CONNECTION
- JOIN TIMEOUT

can we add a list to the wiki page?

Regards,
Max

**Comment by freehuntx** [comment]
ERROR_MAX_CONNECTIONS = Your ip exceeded the maximum connections
I try to make it hard for people to spam bots but if i look at ipv6 this seems to be impossible :/
Maybe you get around this issue if you use ipv6

ERROR_JOIN_TIMEOUT = You did not send the join packet thus you get kicked

I will add the error codes to the documentation.

**Comment by freehuntx** [comment]
Done: https://github.com/freehuntx/gpn-tron/blob/master/ERRORCODES.md
